//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAC.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class donatur
    {
        public int id { get; set; }
        public string item { get; set; }
        public string nama { get; set; }
        public string namamandarin { get; set; }
        public string alamat { get; set; }
        public Nullable<decimal> nominal { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string nomeja { get; set; }
        public string isdisplayed { get; set; }
        public string matauang { get; set; }
    }
}
